[package]
name = "zingy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}
sqlx = { version = "0.8.2", features = [ "runtime-tokio-native-tls" , "postgres" ] }

axum = "0.7.5"
dotenv = "0.15.0"

